# Generated by Django 5.2.7 on 2025-10-27 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categorías de alimentos',
                'db_table': 'categorias_alimentos',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('instrucciones', models.TextField(blank=True)),
                ('porciones', models.IntegerField(default=1)),
                ('calorias_porcion', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('proteinas_porcion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbohidratos_porcion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grasas_porcion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recetas',
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('calorias', models.DecimalField(decimal_places=2, max_digits=6)),
                ('proteinas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbohidratos', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grasas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('porcion_gramos', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alimentos.categoriaalimento')),
            ],
            options={
                'db_table': 'alimentos',
            },
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.alimento')),
            ],
            options={
                'db_table': 'ingredientes_receta',
            },
        ),
    ]
