# Generated by Django 5.2.7 on 2026-02-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0002_initial'),
        ('nutricion', '0005_remove_registroejercicio_id_ejercicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='ingredientereceta',
            name='id_alimento',
        ),
        migrations.RemoveField(
            model_name='ingredientereceta',
            name='id_receta',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='CategoriaAlimento',
        ),
        migrations.DeleteModel(
            name='Alimento',
        ),
        migrations.DeleteModel(
            name='IngredienteReceta',
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
