# Generated by Django 5.2.7 on 2025-10-27 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComidaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comida', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('snack', 'Snack')], max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('calorias', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('proteinas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbohidratos', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grasas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'comidas_diarias',
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('cardio', 'Cardio'), ('fuerza', 'Fuerza'), ('flexibilidad', 'Flexibilidad'), ('otro', 'Otro')], max_length=20)),
                ('calorias_por_hora', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'ejercicios',
            },
        ),
        migrations.CreateModel(
            name='Macronutrientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias_diarias', models.DecimalField(decimal_places=2, max_digits=7)),
                ('proteinas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbohidratos', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grasas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha_calculo', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'macronutrientes',
            },
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('calorias_consumidas', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('proteinas_consumidas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbohidratos_consumidos', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('grasas_consumidas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('agua_litros', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
            options={
                'db_table': 'registro_diario',
            },
        ),
        migrations.CreateModel(
            name='RegistroEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_minutos', models.IntegerField()),
                ('calorias_quemadas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'registro_ejercicios',
            },
        ),
        migrations.CreateModel(
            name='AlimentoConsumido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_gramos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.alimento')),
                ('id_comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.comidadiaria')),
            ],
            options={
                'db_table': 'alimentos_consumidos',
            },
        ),
    ]
