# Generated by Django 5.2.7 on 2025-10-27 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutricion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macronutrientes',
            name='id_perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil'),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='id_perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil'),
        ),
        migrations.AddField(
            model_name='comidadiaria',
            name='id_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.registrodiario'),
        ),
        migrations.AddField(
            model_name='registroejercicio',
            name='id_ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.ejercicio'),
        ),
        migrations.AddField(
            model_name='registroejercicio',
            name='id_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutricion.registrodiario'),
        ),
        migrations.AlterUniqueTogether(
            name='registrodiario',
            unique_together={('id_perfil', 'fecha')},
        ),
    ]
