# Generated by Django 5.2.7 on 2025-12-04 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodiario',
            name='id_macro_objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nutricion.macronutrientes'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='categoria',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('fuerza', 'Fuerza'), ('flexibilidad', 'Flexibilidad'), ('resistencia', 'Resistencia'), ('otro', 'Otro')], max_length=20),
        ),
    ]
