# Generated by Django 5.2.7 on 2026-02-01 18:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0003_registrodiario_id_macro_objetivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodiario',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='id_macro_objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutricion.macronutrientes'),
        ),
    ]
