# Generated by Django 5.2.7 on 2026-02-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0004_alter_registrodiario_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroejercicio',
            name='id_ejercicio',
        ),
        migrations.RemoveField(
            model_name='registroejercicio',
            name='id_registro',
        ),
        migrations.AlterField(
            model_name='comidadiaria',
            name='tipo_comida',
            field=models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('snack', 'Snack')], default='snack', max_length=20),
        ),
        migrations.DeleteModel(
            name='AlimentoConsumido',
        ),
        migrations.DeleteModel(
            name='Ejercicio',
        ),
        migrations.DeleteModel(
            name='RegistroEjercicio',
        ),
    ]
