# Generated by Django 5.2.7 on 2025-10-27 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_sesion', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=20)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso_objetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nivel_actividad', models.CharField(choices=[('sedentario', 'Sedentario'), ('ligero', 'Ligero'), ('moderado', 'Moderado'), ('activo', 'Activo'), ('muy_activo', 'Muy Activo')], default='sedentario', max_length=20)),
                ('objetivo', models.CharField(choices=[('perdida_peso', 'Pérdida de Peso'), ('mantenimiento', 'Mantenimiento'), ('ganancia_muscular', 'Ganancia Muscular')], default='mantenimiento', max_length=20)),
                ('bmr', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('tdee', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='MedidaCorporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_grasa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('id_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
            options={
                'db_table': 'medidas_corporales',
            },
        ),
        migrations.CreateModel(
            name='HistorialObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_anterior', models.CharField(choices=[('perdida_peso', 'Pérdida de Peso'), ('mantenimiento', 'Mantenimiento'), ('ganancia_muscular', 'Ganancia Muscular')], max_length=20)),
                ('objetivo_nuevo', models.CharField(choices=[('perdida_peso', 'Pérdida de Peso'), ('mantenimiento', 'Mantenimiento'), ('ganancia_muscular', 'Ganancia Muscular')], max_length=20)),
                ('peso_en_cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('id_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
            options={
                'db_table': 'historial_objetivos',
            },
        ),
    ]
