# Generated by Django 5.2.7 on 2026-02-01 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfil_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medidacorporal',
            name='id_perfil',
        ),
        migrations.DeleteModel(
            name='HistorialObjetivo',
        ),
        migrations.DeleteModel(
            name='MedidaCorporal',
        ),
    ]
