# Generated by Django 5.2.7 on 2025-10-27 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ia_chat', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionia',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensajeia',
            name='id_conversacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ia_chat.conversacionia'),
        ),
        migrations.AddField(
            model_name='recomendacionia',
            name='id_perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil'),
        ),
    ]
